# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
__all__ = [
    "nested_spans",
    "traced_function",
    "traced_with_attributes",
]

def nested_spans() -> None:
    r"""
    A traced function that calls nested spans.
    """

def traced_function() -> builtins.int:
    r"""
    A simple traced function that does some work.
    """

def traced_with_attributes(name: builtins.str, count: builtins.int) -> None:
    r"""
    A traced function that emits events with attributes.
    """

