[build-system]
requires = ["maturin>=1.13.3,<2.0"]
build-backend = "maturin"

[project]
name = "example-module"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "opentelemetry-api>=1.42.1",
    "opentelemetry-sdk>=1.20",
]

[dependency-groups]
dev = [
    "pytest>=9.0.3",
    "maturin>=1.13.3,<2.0",
    "syrupy>=5.2.0",
    "pyright>=1.1.409",
]

[tool.maturin]
features = ["pyo3/extension-module"]
